services:
  redis-server:
    container_name: redis-server
    image: redis:8.0.0
    restart: unless-stopped
    networks:
      - redis_network
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOSTS: redis-server
    networks:
      - redis_network
    ports:
      - "127.0.0.1:8083:8081"
    depends_on:
      - redis-server

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    name: redis_network
