---
- name: Create redis directory
  ansible.builtin.file:
    path: /opt/docker-stack/infrastructure/redis
    state: directory
    mode: "0755"

- name: Copy redis docker-compose.yml
  ansible.builtin.copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /opt/docker-stack/infrastructure/redis/docker-compose.yml
    mode: "0644"

- name: Copy .env
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.env"
    dest: /opt/docker-stack/infrastructure/redis/.env
    mode: "0644"

- name: Ensure Docker Compose is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Run docker-compose up in redis directory
  community.docker.docker_compose_v2:
    project_src: /opt/docker-stack/infrastructure/redis
    env_files: /opt/docker-stack/infrastructure/redis/.env
    state: present
