---
- name: Create directory for Redis
  ansible.builtin.file:
    path: "/opt/docker-stack/infrastructure/redis"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: Copy docker-compose file to server
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "/opt/docker-stack/infrastructure/redis/docker-compose.yml"
    mode: "0644"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: Copy .env
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.env"
    dest: /opt/docker-stack/infrastructure/redis/.env
    mode: "0644"

- name: Ensure Docker Compose is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Deploy Redis containers with docker-compose
  community.docker.docker_compose_v2:
    project_src: "/opt/docker-stack/infrastructure/redis"
    pull: always
    recreate: always
    remove_orphans: true
    state: present
# - name: Verify Redis container health
#   community.docker.docker_container_info:
#     name: redis-db
#   register: container_info
#   until: container_info is defined and
#     container_info.container is defined and
#     container_info.container.State is defined and
#     container_info.container.State.Health is defined and
#     (container_info.container.State.Health.Status == "healthy" or container_info.container.State.Health.Status == "starting")
#   retries: 10
#   delay: 10
