services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: auto_heal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /run/docker.sock:/var/run/docker.sock
