services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: auto_heal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "pgrep", "autoheal"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    networks:
      - autoheal_network
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-998}"

networks:
  autoheal_network:
    driver: bridge
