---
- name: Ensure required groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users | selectattr('groups', 'defined') | map(attribute='groups') | flatten | unique }}"

- name: Create users with advanced configuration
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups | default([]) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    createhome: true
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(false) }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure SSH directory
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ users }}"
  when: item.ssh_key is defined

- name: Add SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  loop: "{{ users }}"
  when: item.ssh_key is defined
