---
- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: dist
    cache_valid_time: 3600
  become: true
