---
- name: Create Traefik configuration directory
  ansible.builtin.file:
    path: /opt/traefik
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create Traefik log directory
  ansible.builtin.file:
    path: /opt/traefik/log
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy Traefik static configuration (traefik.yml)
  ansible.builtin.template:
    src: traefik.yml
    dest: /opt/traefik/traefik.yml
    mode: "0644"
    owner: root
    group: root
  notify: Restart Traefik

- name: Create .env file for Cloudflare credentials
  ansible.builtin.template:
    src: traefik.env.j2 # A new template file to be created
    dest: /opt/traefik/.env
    mode: "0600" # Secure permissions
    owner: root
    group: root
  notify: Restart Traefik

- name: Copy Traefik Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /opt/traefik/docker-compose.yml
    mode: "0644"
    owner: root
    group: root
  notify: Restart Traefik

- name: Ensure 'web' network exists
  community.docker.docker_network:
    name: web
    state: present

- name: Bring up Traefik service
  community.docker.docker_compose:
    project_src: /opt/traefik
    state: present
    pull: true
  notify: Restart Traefik
