# roles/traefik-setup/tasks/main.yml
---
- name: Create Traefik configuration directory
  ansible.builtin.file:
    path: /opt/docker-stack/infrastructure/traefik
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create Traefik log directory
  ansible.builtin.file:
    path: /opt/docker-stack/infrastructure/traefik/log
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create dynamic configuration directory
  ansible.builtin.file:
    path: /etc/traefik/dynamic
    state: directory
    mode: "0755"
    owner: root
    group: root
  notify: Restart Traefik

- name: Copy Traefik static configuration (traefik.yml)
  ansible.builtin.template:
    src: traefik.yml
    dest: /opt/docker-stack/infrastructure/traefik/traefik.yml
    mode: "0644"
    owner: root
    group: root
  notify: Restart Traefik

- name: Create .env file for Cloudflare credentials
  ansible.builtin.template:
    src: traefik.env.j2
    dest: /opt/docker-stack/infrastructure/traefik/.env
    mode: "0600"
    owner: root
    group: root
  notify: Restart Traefik

- name: Copy Traefik Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /opt/docker-stack/infrastructure/traefik/docker-compose.yml
    mode: "0644"
    owner: root
    group: root
  notify: Restart Traefik

- name: Bring up Traefik service
  community.docker.docker_compose_v2:
    project_src: /opt/docker-stack/infrastructure/traefik
    state: present
    pull: always
  notify: Restart Traefik
