---
- name: Create autoheal directory
  ansible.builtin.file:
    path: /opt/docker-stack/infrastructure/autoheal
    state: directory
    mode: "0755"

- name: Copy autoheal docker-compose.yml
  ansible.builtin.copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /opt/docker-stack/infrastructure/autoheal/docker-compose.yml
    mode: "0644"

- name: Ensure Docker Compose is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Run docker-compose up in autoheal directory
  community.docker.docker_compose_v2:
    project_src: /opt/docker-stack/infrastructure/autoheal
    state: present
