---
- name: Ensure Git is installed
  ansible.builtin.package:
    name: git
    state: present
    update_cache: true

- name: Install Git extras if available
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ git_extra_packages }}"
  register: git_extras_install
  failed_when:
    - git_extras_install.failed
    - "'not found' not in git_extras_install.msg"

- name: Configure Git global user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  become: false
  when: git_config_global | default(true)

- name: Configure Git global user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  become: false
  when: git_config_global | default(true)

- name: Set Git default branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  become: false

- name: Configure Git core settings
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: "pull.rebase", value: "true" }
    - { name: "core.editor", value: "nano" }
  become: false

- name: Create global Git ignore file
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    mode: "0644"
    content: |
      # Compiled source #
      *.pyc
      *.class
      *.dll
      *.exe
      *.o
      *.so

      # Packages #
      *.7z
      *.dmg
      *.gz
      *.iso
      *.jar
      *.rar
      *.tar
      *.zip

      # Logs and databases #
      *.log
      *.sqlite

      # OS generated files #
      .DS_Store
      .DS_Store?
      ._*
      .Spotlight-V100
      .Trashes
      ehthumbs.db
      Thumbs.db
  become: false

- name: Configure global Git ignore
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore_global"
  become: false
